-- For this problem, we will consider a manager an employee who has at least 1 other employee reporting to them.
-- Write an SQL query to report the ids and the names of all managers, the number of employees who report directly to them, and the average age of the reports rounded to the nearest integer.
-- Return the result table ordered by employee_id.